name: Build Custom Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag for the custom image"
        required: true
      push:
        description: "Push the built image to GitHub/DockerHub Container Registry"
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Prepare variables
        id: vars
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const version = '${{ inputs.version }}'
            const semverRegex = /^v?\d+\.\d+\.\d+(-\S+)?$/

            if (!semverRegex.test(version)) {
              core.setFailed(`Invalid version format: ${version}. Expected format: X.Y.Z or vX.Y.Z`)
              return
            }

            core.setOutput('version', version);
            core.setOutput('readmeExist', fs.existsSync('NOTE.md'));

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            aliuq/memos
            ghcr.io/aliuq/memos
          tags: |
            type=semver,pattern={{version}},value=${{ steps.vars.outputs.version }}
          labels: |
            org.opencontainers.image.upstream=https://github.com/usememos/memos
          annotations: |
            org.opencontainers.image.upstream=https://github.com/usememos/memos

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          use: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push README
        if: ${{ fromJson(steps.vars.outputs.readmeExist) && inputs.push }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: aliuq/memos
          short-description: "An open-source, self-hosted note-taking service. Your thoughts, your data, your control â€” no tracking, no ads, no subscription fees."
          readme-filepath: ./NOTE.md

      - name: Notification
        uses: aliuq/telegram-action@v1
        if: ${{ inputs.push }}
        with:
          bot_token: ${{ secrets.BOT_TOKEN }}
          chat_id: ${{ secrets.CHAT_ID }}
          reply_to_message_id: ${{ secrets.REPLY_TO_MESSAGE_ID }}
          message: |
            ðŸŽ‰ Memo has new image builds

            ```txt
            ${{ steps.meta.outputs.tags }}
            ```

            #build_image #memos #docker
          buttons: |
            [
              [
                { "text": "Repository", "url": "https://github.com/${{ github.repository }}" },
                { "text": "Actions Run", "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }
              ],
              [
                { "text": "DockerHub", "url": "https://hub.docker.com/r/aliuq/memos" }
              ]
            ]
